# LAB | Ensemble Methods

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In this Lab, you should try different ensemble methods in order to see if can obtain a better model than before. In order to do a fair comparison, you should perform the same feature scaling, engineering applied in previous Lab.

In [53]:
#Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
from sklearn.ensemble import AdaBoostClassifier

In [2]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

Now perform the same as before:
- Feature Scaling
- Feature Selection


In [3]:
df=spaceship
df.shape

(8693, 14)

In [4]:
df.dtypes

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

In [5]:
df.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df['Cabin'] = df['Cabin'].str[0]
df['Cabin'].value_counts()

Cabin
F    2152
G    1973
E     683
B     628
C     587
D     374
A     207
T       2
Name: count, dtype: int64

In [10]:
#eliminar columnas PassengerId, Name
df.drop(columns=['PassengerId','Name'],inplace=True)


In [11]:
df['Destination']=df['Destination'].str.strip()
df=pd.get_dummies(df,columns=['Destination'],drop_first=True)

In [12]:
df=pd.get_dummies(df,columns=['CryoSleep'],drop_first=True)


In [13]:
df=pd.get_dummies(df,columns=['VIP'],drop_first=True)

In [14]:
#hacer dummies de la columna HomePlanet
df=pd.get_dummies(df,columns=['HomePlanet'],drop_first=True)

In [15]:
df=pd.get_dummies(df,columns=['Cabin'],drop_first=True)

In [16]:
df['CryoSleep_True']=df['CryoSleep_True'].astype('int')
df['VIP_True']=df['VIP_True'].astype('int')
df['HomePlanet_Europa']=df['HomePlanet_Europa'].astype('int')
df['HomePlanet_Mars']=df['HomePlanet_Mars'].astype('int')
df['Destination_PSO J318.5-22']=df['Destination_PSO J318.5-22'].astype('int')
df['Destination_TRAPPIST-1e']=df['Destination_TRAPPIST-1e'].astype('int')
df['Transported']=df['Transported'].astype('int')

In [17]:
cabin_columns = ['Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E', 'Cabin_F', 'Cabin_G', 'Cabin_T']
df[cabin_columns] = df[cabin_columns].astype(int)


**Perform Train Test Split**

In [18]:
X = df.drop(columns=['Transported'])
y = df['Transported']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**Model Selection** - now you will try to apply different ensemble methods in order to get a better model

- Bagging and Pasting

In [ ]:
#Bagging: muestra con reemplazo( cada muestra se puede repetir en el subconjunto o no aparecer), Pasting:muestras sin reemplazo osea que no ser repiten

In [ ]:
#bagging
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

bagging = BaggingClassifier(DecisionTreeClassifier(), n_estimators=100, max_samples=0.5, max_features=0.5)
bagging.fit(X_train, y_train)


BaggingClassifier(estimator=DecisionTreeClassifier(), max_features=0.5,
                  max_samples=0.5, n_estimators=100)

In [31]:
# Predict the labels of the test set: y_pred
y_pred = bagging.predict(X_test)
accuracy_score(y_test, y_pred)




0.800302571860817

In [32]:
#precision
precision_score(y_test, y_pred)


0.8091603053435115

In [39]:
#recall
recall_score(y_test, y_pred)

0.7922272047832586

In [35]:
#f1
f1_score(y_test, y_pred, average=None)

array([0.8       , 0.80060423])

In [52]:
#clasification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.81      0.80       653
           1       0.81      0.79      0.80       669

    accuracy                           0.80      1322
   macro avg       0.80      0.80      0.80      1322
weighted avg       0.80      0.80      0.80      1322



- Random Forests

In [ ]:
#ramdon forest
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)





0.8018154311649016

In [40]:
#precision del ramdon forest
y_pred_rf = rf.predict(X_test)
precision_score(y_test, y_pred_rf)


0.8155038759689922

In [41]:
#recall del ramdon forest
recall_score(y_test, y_pred_rf)


0.7862481315396114

In [26]:
#f1 score del ramdon forest
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)


0.8006088280060882

In [51]:
#clasification report
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.79      0.82      0.80       653
           1       0.82      0.79      0.80       669

    accuracy                           0.80      1322
   macro avg       0.80      0.80      0.80      1322
weighted avg       0.80      0.80      0.80      1322



- Gradient Boosting

In [45]:
gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb.fit(X_train, y_train)
gb.score(X_test, y_test)

0.8071104387291982

In [46]:
 #precision
y_pred_gb_= gb.predict(X_test)
precision_score(y_test, y_pred_gb_, average=None)

array([0.83728814, 0.78278689])

In [47]:
#recall
recall_score(y_test, y_pred_gb_, average=None)

array([0.75650842, 0.85650224])

In [48]:
#f1
f1_score(y_test, y_pred_gb_, average=None)

array([0.79485117, 0.81798715])

In [ ]:
#clasiification report
print(classification_report(y_test, y_pred_gb_))

              precision    recall  f1-score   support

           0       0.84      0.76      0.79       653
           1       0.78      0.86      0.82       669

    accuracy                           0.81      1322
   macro avg       0.81      0.81      0.81      1322
weighted avg       0.81      0.81      0.81      1322



- Adaptive Boosting

In [54]:
ada = AdaBoostClassifier(n_estimators=100, random_state=42)
ada.fit(X_train, y_train)
ada.score(X_test, y_test)

0.7859304084720121

In [ ]:
#precision
y_pred_ada = ada.predict(X_test)
precision_score(y_test, y_pred_ada, average=None)

array([0.78030303, 0.79154079])

In [56]:
#recall
recall_score(y_test, y_pred_ada, average=None)


array([0.78866769, 0.78325859])

In [57]:
#f1
f1_score(y_test, y_pred_ada, average=None)

array([0.78446306, 0.78737791])

In [58]:
##clasification report
print(classification_report(y_test, y_pred_ada))

              precision    recall  f1-score   support

           0       0.78      0.79      0.78       653
           1       0.79      0.78      0.79       669

    accuracy                           0.79      1322
   macro avg       0.79      0.79      0.79      1322
weighted avg       0.79      0.79      0.79      1322



Which model is the best and why?

In [59]:
#El GradientBoostingClassifier es el modelo que mejor se ajusta a los datos, ya que tiene un mayor accuracy, precision, recall y f1 score